# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e73532c9-c7ff-44ae-8f8e-b9624f6c7887";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e73532c9-c7ff-44ae-8f8e-b9624f6c7887".device = "/dev/disk/by-uuid/e73532c9-c7ff-44ae-8f8e-b9624f6c7887";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ACA3-C99C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-bc4b7c5e-f234-48cd-9edf-01d7ea06bff9"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
