# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    { device = "/dev/mapper/luks-0c2b5412-9dd5-4efd-8e68-cd34ca5d7a0f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0c2b5412-9dd5-4efd-8e68-cd34ca5d7a0f".device = "/dev/disk/by-uuid/0c2b5412-9dd5-4efd-8e68-cd34ca5d7a0f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CFD5-6788";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
