# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
  };

  fileSystems."/" = {
    device = "/dev/mapper/luks-0fb68fbd-73ac-48df-a9df-f7fc119ab41c";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-0fb68fbd-73ac-48df-a9df-f7fc119ab41c".device = "/dev/disk/by-uuid/0fb68fbd-73ac-48df-a9df-f7fc119ab41c";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/298E-484D";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-6bf5b651-af04-48b2-b09e-b62eb02653ab";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
