name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  flake-check:
    runs-on: self-hosted
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Run flake check
        run: nix flake check
